name=Pressure sensor library
version=0.0.1
author=Babatunde Adegoke
maintainer=Babatunde <tunashapcb@gmail.com>
sentence=Creates a software I2C/TWI bus on every pins. 
paragraph=The Pressure sensor library is compartible with different arduino boards
category=Device Control
url=https://github.com/Tunasha/Presure-Sensor-Library
architectures=*
