name=TunashaHydrostaticPressureSensor
version=0.0.1
author=Babatunde Adegoke
maintainer=Babatunde Adegoke
sentence=Reads pressure sensors to measure liquid level in a tank.
paragraph=A cross-platform Arduino library for interfacing with hydrostatic pressure sensors and calculating liquid level in a tank. Compatible with a range of Arduino boards.
category=Sensors
url=https://github.com/Tunasha/TunashaHydrostaticPressureSensor
architectures=*
